Repository slipstream/SlipStreamJobEngine, pull requests merged in 2018-08, with the labels that each got.

#38 virtual_machines_collect: improved service offer search
  job/src/slipstream/job/actions/virtual_machines_collect.py
Labels: S40 Ready to validate, T3 Enhancement

#41 register SIGUSR1 signal to log stack trace of all threads
  README.md
  job/src/slipstream/job/base.py
  job/src/slipstream/job/executor.py
  job/src/slipstream/job/util.py
Labels: S40 Ready to validate

#43 Update executor.py
  job/src/slipstream/job/executor.py
  job/src/slipstream/job/job.py
Labels: S40 Ready to validate

#44 add job for collecting storage buckets
  job/requirements.txt
  job/src/scripts/job_distributor_storage_buckets_collect.py
  job/src/slipstream/job/actions/storage_buckets_collect.py
  rpm/pom.xml
Labels: P80 HNSciCloud-RHEA, S40 Ready to validate

#45 Executor thread lock still present new workaround
  job/src/slipstream/job/executor.py
Labels: P45 MF2C, S40 Ready to validate, T5 Bug

#47 fix object store endpoint Fail
  job/src/slipstream/job/actions/storage_buckets_collect.py
Labels: S40 Ready to validate

#46 Bug fix
  job/src/slipstream/job/actions/storage_buckets_collect.py
  job/src/slipstream/job/actions/virtual_machines_collect.py
Labels: S40 Ready to validate

#49 Thread lock fix2
  job/src/slipstream/job/actions/dummy_test_action.py
  job/src/slipstream/job/actions/quotas_collect.py
  job/src/slipstream/job/actions/storage_buckets_collect.py
  job/src/slipstream/job/actions/virtual_machines_cleanup.py
  job/src/slipstream/job/actions/virtual_machines_collect.py
Labels: S40 Ready to validate

#50 remove unit from cimi resource
  job/src/slipstream/job/actions/storage_buckets_collect.py
Labels: S40 Ready to validate

#52 Add resource:type attribute from service offer
  job/src/slipstream/job/actions/storage_buckets_collect.py
  job/src/slipstream/job/actions/virtual_machines_collect.py
Labels: P80 HNSciCloud-RHEA, S40 Ready to validate

#53 Enhancement logging
  job/src/scripts/job_distributor_dummy_test_action.py
  job/src/scripts/job_distributor_jobs_cleanup.py
  job/src/scripts/job_distributor_nb_state_snaps_cleanup.py
  job/src/scripts/job_distributor_quotas_collect.py
  job/src/scripts/job_distributor_storage_buckets_collect.py
  job/src/scripts/job_distributor_vms_cleanup.py
  job/src/scripts/job_distributor_vms_collect.py
  job/src/slipstream/job/actions/__init__.py
  job/src/slipstream/job/actions/dummy_test_action.py
  job/src/slipstream/job/actions/jobs_cleanup.py
  job/src/slipstream/job/actions/nuvlabox_state_snapshots_cleanup.py
  job/src/slipstream/job/actions/quotas_collect.py
  job/src/slipstream/job/actions/storage_buckets_collect.py
  job/src/slipstream/job/actions/virtual_machines_cleanup.py
  job/src/slipstream/job/actions/virtual_machines_collect.py
  job/src/slipstream/job/base.py
  job/src/slipstream/job/distributor.py
  job/src/slipstream/job/executor.py
  job/src/slipstream/job/job.py
  job/src/slipstream/job/util.py
Labels: S40 Ready to validate

#55 Copy the price:currency one level up from serviceOffer
  job/src/slipstream/job/actions/virtual_machines_collect.py
Labels: P80 HNSciCloud-RHEA, S40 Ready to validate
